import type { DetectedChain } from "./types.js";
import { getInstallationOctokit } from "./github.js";

export interface AlertConfig {
  alertRepo: string;    // "owner/repo" where issues are created
  appId: string;        // GitHub App ID
  privateKey: string;   // GitHub App private key (PEM)
}

/** Handle a detected attack chain by creating a GitHub issue */
export async function handleChainAlert(
  chain: DetectedChain,
  config: AlertConfig,
): Promise<void> {
  const [owner, repo] = config.alertRepo.split("/");

  try {
    const octokit = await getInstallationOctokit(owner, repo, config.appId, config.privateKey);

    const title = `\ud83d\udea8 Attack chain detected: ${chain.pattern.name}`;
    const body = buildChainIssueBody(chain);

    const result = await octokit.issues.create({
      owner,
      repo,
      title,
      body,
      labels: ["security", "jibril", "attack-chain"],
    });

    console.log(
      `[alert] Created issue #${result.data.number} in ${config.alertRepo} for chain ${chain.pattern.name} (confidence: ${(chain.confidence * 100).toFixed(0)}%)`,
    );
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error(`[alert] Failed to create issue for chain ${chain.pattern.id}: ${msg}`);
  }
}

/** Build a structured issue body for an attack chain */
function buildChainIssueBody(chain: DetectedChain): string {
  const sections: string[] = [
    `## \ud83d\udd17 Attack Chain: ${chain.pattern.name}`,
    "",
    `> ${chain.pattern.description}`,
    "",
    `| Field | Value |`,
    `|-------|-------|`,
    `| **Confidence** | ${(chain.confidence * 100).toFixed(0)}% |`,
    `| **Scope** | \`${chain.scope}\` |`,
    `| **First seen** | ${new Date(chain.firstSeen).toISOString()} |`,
    `| **Last seen** | ${new Date(chain.lastSeen).toISOString()} |`,
    `| **Events in chain** | ${chain.matchedEvents.length} |`,
    "",
    "## Kill Chain Progression",
    "",
    "```",
    chain.matchedEvents
      .map((e, i) => `Step ${i + 1}: ${e.event.metadata.tactic} \u2192 ${e.event.metadata.name}`)
      .join("\n"),
    "```",
    "",
    "## Event Details",
  ];

  for (const [i, event] of chain.matchedEvents.entries()) {
    const e = event.event;
    const eventSection = [
      "",
      `### Step ${i + 1}: ${e.metadata.tactic} \u2014 ${e.metadata.name}`,
      "",
      `| Field | Value |`,
      `|-------|-------|`,
      `| **Kind** | \`${e.metadata.kind}\` |`,
      `| **Severity** | ${e.score.severity_level} (${e.score.severity}/100) |`,
      `| **Confidence** | ${e.score.confidence} |`,
      `| **MITRE ATT&CK** | ${e.metadata.tactic} / ${e.metadata.technique}${e.metadata.subtechnique ? ` / ${e.metadata.subtechnique}` : ""} |`,
      `| **Timestamp** | ${e.timestamp} |`,
      `| **UUID** | \`${event.id}\` |`,
    ];

    if (e.exec) {
      eventSection.push(`| **Command** | \`${e.exec.cmdline ?? e.exec.cmd}\` |`);
    }
    if (e.file) {
      eventSection.push(`| **File** | \`${e.file.file}\` (${e.file.actions.join(", ")}) |`);
    }
    if (e.network) {
      eventSection.push(`| **Network** | ${e.network.destination_ip ?? "?"}:${e.network.destination_port ?? "?"} |`);
      if (e.network.domain) {
        eventSection.push(`| **Domain** | ${e.network.domain} |`);
      }
    }
    if (e.container) {
      eventSection.push(`| **Container** | ${e.container.container_name ?? e.container.container_id ?? "unknown"} |`);
      eventSection.push(`| **Image** | ${e.container.image ?? "unknown"}:${e.container.image_tag ?? "latest"} |`);
    }
    if (e.base?.background?.ancestry?.length) {
      const chain = e.base.background.ancestry.map(a => `\`${a.cmd}\``).join(" \u2192 ");
      eventSection.push("", `**Process ancestry**: ${chain}`);
    }

    sections.push(...eventSection);
  }

  sections.push(
    "",
    "## Recommended Actions",
    "",
    "1. **Verify** the attack chain \u2014 review each step to confirm it's a true positive",
    "2. **Contain** \u2014 isolate the affected container/host if the chain is confirmed",
    "3. **Investigate** \u2014 use `@jibril chain " + chain.id.slice(0, 8) + "` in Copilot Chat for detailed LLM analysis",
    "4. **Remediate** \u2014 address the root cause (vulnerable dependency, misconfigured permission, etc.)",
    "",
    "---",
    "*Auto-generated by [Jibril Correlation Agent](https://github.com/samueltauil/jibril-correlation-agent) \u2014 Runtime\u2192Code security correlation powered by Jibril eBPF*",
  );

  return sections.join("\n");
}
